import type { MetadataRoute } from 'next'
import { getSiteUrl } from '@/lib/seo/config'

export default function robots(): MetadataRoute.Robots {
  const siteUrl = getSiteUrl()

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/dashboard/',
          '/customer-portal/',
          '/inventory/',
          '/products/',
          '/purchases/',
          '/suppliers/',
          '/sales/',
          '/payments/',
          '/customers/',
          '/returns/',
          '/expenses/',
          '/reports/',
          '/goods-receipts/',
          '/ai-assistant/',
          '/api/',
          '/login',
        ],
      },
      {
        userAgent: 'GPTBot',
        allow: '/',
        disallow: [
          '/dashboard/',
          '/customer-portal/',
          '/inventory/',
          '/products/',
          '/purchases/',
          '/suppliers/',
          '/sales/',
          '/payments/',
          '/customers/',
          '/returns/',
          '/expenses/',
          '/reports/',
          '/goods-receipts/',
          '/ai-assistant/',
          '/api/',
          '/login',
        ],
      },
      {
        userAgent: 'PerplexityBot',
        allow: '/',
        disallow: [
          '/dashboard/',
          '/customer-portal/',
          '/inventory/',
          '/products/',
          '/purchases/',
          '/suppliers/',
          '/sales/',
          '/payments/',
          '/customers/',
          '/returns/',
          '/expenses/',
          '/reports/',
          '/goods-receipts/',
          '/ai-assistant/',
          '/api/',
          '/login',
        ],
      },
      {
        userAgent: 'ClaudeBot',
        allow: '/',
        disallow: [
          '/dashboard/',
          '/customer-portal/',
          '/inventory/',
          '/products/',
          '/purchases/',
          '/suppliers/',
          '/sales/',
          '/payments/',
          '/customers/',
          '/returns/',
          '/expenses/',
          '/reports/',
          '/goods-receipts/',
          '/ai-assistant/',
          '/api/',
          '/login',
        ],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  }
}
